#!/usr/bin/env bash
# SRT Restreamer — one-command start (development / single host).
#
# What it does:
#   1. Creates a virtualenv and installs dependencies (cached).
#   2. Creates .env with generated secrets on first run.
#   3. Creates the admin user on first run (prints credentials once,
#      or uses ADMIN_USERNAME/ADMIN_PASSWORD if you export them).
#   4. Starts the application.
#
# Usage:
#   bash start.sh
set -euo pipefail
cd "$(dirname "$0")"

# ---------- 1. virtualenv ----------
if [ -x .venv/Scripts/python.exe ]; then
    PY=.venv/Scripts/python.exe
elif [ -x .venv/Scripts/python ]; then
    PY=.venv/Scripts/python
elif [ -x .venv/bin/python ]; then
    PY=.venv/bin/python
else
    echo "[*] Creating virtualenv (.venv)..."
    python -m venv .venv
    if [ -x .venv/Scripts/python.exe ]; then
        PY=.venv/Scripts/python.exe
    else
        PY=.venv/bin/python
    fi
fi

echo "[*] Installing dependencies (cached)..."
"$PY" -m pip install -q -r backend/requirements.txt

# ---------- 2. .env ----------
if [ ! -f .env ]; then
    echo "[*] Creating .env with generated secrets..."
    SECRET_KEY=$("$PY" -c 'import secrets; print(secrets.token_urlsafe(32))')
    SECRETS_KEY=$("$PY" -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')
    cat > .env <<EOF
# Generated by start.sh — do not commit.
SECRET_KEY=$SECRET_KEY
SECRETS_KEY=$SECRETS_KEY
APP_BASE_URL=
DATABASE_URL=sqlite:///data/restreamer.db
DATA_DIR=data
UVICORN_HOST=0.0.0.0
UVICORN_PORT=8080
# Local development over HTTP. Set to true behind a TLS reverse proxy.
SESSION_COOKIE_SECURE=false
SRT_LISTENER_PORT_RANGE=5000-10100
INTERNAL_PORT_START=40000
INTERNAL_PORT_END=49999
EOF
fi

set -a
# shellcheck disable=SC1091
source .env
set +a

# ---------- 3. admin bootstrap ----------
if ! PYTHONPATH="$PWD/backend" "$PY" - <<'PYEOF'
import sys
from models import init_db, get_db, User
init_db()
db = next(get_db())
try:
    sys.exit(0 if db.query(User).first() else 1)
finally:
    db.close()
PYEOF
then
    echo "[*] No admin user found, creating one..."
    if [ -n "${ADMIN_PASSWORD:-}" ]; then
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}" ADMIN_PASSWORD="$ADMIN_PASSWORD" \
            PYTHONPATH="$PWD/backend" "$PY" backend/bootstrap_admin.py
    else
        GEN_PASS=$("$PY" -c 'import secrets; print(secrets.token_urlsafe(16))')
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}" ADMIN_PASSWORD="$GEN_PASS" \
            PYTHONPATH="$PWD/backend" "$PY" backend/bootstrap_admin.py
        echo ""
        echo "=== Generated admin credentials (SAVE THEM NOW) ==="
        echo "    username: ${ADMIN_USERNAME:-admin}"
        echo "    password: $GEN_PASS"
        echo "===================================================="
        echo ""
    fi
fi

# ---------- 4. run ----------
export PYTHONPATH="$PWD/backend"
echo "[*] Starting SRT Restreamer at http://localhost:${UVICORN_PORT:-8080}/login"
exec "$PY" backend/main.py
